services:
  backend:
    container_name: laravel_backend
    build:
      context: .
      dockerfile: .docker/laravel/Dockerfile
    volumes:
      - ./.docker/laravel/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./.docker/laravel/supervisor/queue-worker.conf:/etc/supervisor/conf.d/queue-worker.conf
      - ./.docker/laravel/supervisor/php-fpm.conf:/etc/supervisor/conf.d/php-fpm.conf
      - ./.docker/laravel/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./:/var/www:delegated
    healthcheck:
      test: [ 'CMD', 'php-fpm', '-t' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s